services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "3000:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  artist-srv:
    image: eggiel/lernfair-app_vers1:BackendVers1  # Ersetze <tag> durch das korrekte Tag aus deinem Docker Hub
    container_name: my_fastapi_container
    depends_on:
      - mongodb
    ports:
      - "8000:8000"
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
